version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "2181"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  journey_telegram_bot:
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      journey_core_nlp:
        condition: service_started
    build:
      context: ./
      dockerfile: ./channels/JourneyTelegramBot/Dockerfile
  rasa:
    container_name: rasa
    stdin_open: true
    tty: true
    image: khalosa/rasa-aarch64:3.2.5
    ports:
      - 5005:5005
    volumes:
      - ./journey_core_nlp:/app
  journey_core_nlp:
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./journey_core_nlp
    volumes:
      - ./journey_core_nlp:/app
    expose:
      - 5005

  journey_central_database:
    restart: always
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_journey
      MYSQL_USER: Journey
      MYSQL_PASSWORD: test_password123
    command: --init-file /var/lib/mysql_journey/init.sql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root --password=root"
      timeout: 20s
      retries: 10
    volumes:
      - journey-central-db:/var/lib/mysql_journey
      - ./init.sql:/var/lib/mysql_journey/init.sql

  journey_central:
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
      journey_central_database:
        condition: service_started
    build:
      context: ./journey_central
    volumes:
      - ./journey_central:/workspace/app
  trello_integration:
    depends_on:
      - journey_central
    build:
      context: ./integrations/trello
    volumes:
      - ./integrations/trello:/app

volumes:
  journey-central-db: