version: '3.8'
services:
  backend:
    container_name: journey_central
    restart: on-failure
    build: ./journey_central
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://journey_database:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    tty: true
    stdin_open: true
    volumes:
      - .m2:/root/.m2
    depends_on:
      - journey_database
  journey_database:
    #container_name: journey_central_db
    restart: unless-stopped
    image: mysql:5.7
    command: --init-file /var/lib/mysql_journey/init.sql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
        MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQLDB_DATABASE
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/var/lib/mysql_journey/init.sql
  journey_nlp:
    build: ./journey_core_nlp
    ports:
      - 7150:7150

volumes:
  my-db:
  data01: